### ISSUE TITLE
on first docker-compose up -d container mytaiga_taiga exits immediately.

### ISSUE THREAD

**Issue by chamunks** [benhutchins/docker-taiga#6]
The following comes out of docker logs -f mytaiga_taiga_1

https://gist.github.com/chamunks/237c155c8fbe8cf932df

**Comment by nykopol** [comment]
same problem for me

**Comment by jasl8r** [comment]
For some reason the Taiga docker image is using a very old version, or at least very old versions of the deps.  The error:

    File "/usr/local/lib/python3.4/site-packages/django_jinja/base.py", line 12, in <module>
        from django.template import Origin
    ImportError: cannot import name 'Origin'

Looks like it is from django-jinja circa version 1.0.5, but Taiga uses version 1.4.1.  I assume this must be due to a bad docker build and push from @benhutchins.

https://github.com/niwinz/django-jinja/commit/c99ca556aa0049677a847a81d8f9a7baf0beb160

**Comment by benhutchins** [comment]
I was able to reproduce this, it appears that the database was not started by the time the Taiga attempts to initialize the database.

You can try running:

    docker-compose up -d postgres
    sleep 10
    docker-compose up -d

This should give the database enough time to initialize.

**Comment by benhutchins** [comment]
@jasl8r You can always pull this and rebuild the image yourself, however you're right that Taiga defines its dependencies in [requirements.txt](https://github.com/taigaio/taiga-back/blob/stable/requirements.txt), which wants to use `django-jinja==1.4.1`. I however am seeing that the latest docker image has the correct dependency versions installed.

```
Requirement already up-to-date: Django==1.8.6 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: django-picklefield==0.3.2 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: django-sampledatahelper==0.3.0 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: gunicorn==19.3.0 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: psycopg2==2.6.1 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: Pillow==2.9.0 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: pytz==2015.7 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: six==1.10.0 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: amqp==1.4.7 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: djmail==0.11 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: django-pgjson==0.3.1 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: djorm-pgarray==1.2 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: django-jinja==1.4.1 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: jinja2==2.8 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 14))
Requirement already up-to-date: pygments==2.0.2 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 15))
Requirement already up-to-date: django-sites==0.8 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 16))
Requirement already up-to-date: Markdown==2.6.4 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 17))
Requirement already up-to-date: fn==0.4.3 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 18))
Requirement already up-to-date: diff-match-patch==20121119 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 19))
Requirement already up-to-date: requests==2.8.1 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 20))
Requirement already up-to-date: django-sr==0.0.4 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 21))
Requirement already up-to-date: easy-thumbnails==2.2.1 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 22))
Requirement already up-to-date: celery==3.1.19 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 23))
Requirement already up-to-date: redis==2.10.3 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 24))
Requirement already up-to-date: Unidecode==0.04.18 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 25))
Requirement already up-to-date: raven==5.8.1 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 26))
Requirement already up-to-date: bleach==1.4.2 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 27))
Requirement already up-to-date: django-ipware==1.1.2 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 28))
Requirement already up-to-date: premailer==2.9.6 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 29))
Requirement already up-to-date: cssutils==1.0.1 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 30))
Requirement already up-to-date: django-transactional-cleanup==0.1.15 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 31))
Requirement already up-to-date: lxml==3.5.0b1 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 32))
Requirement already up-to-date: pyjwkest==1.0.7 in /usr/local/lib/python3.4/site-packages (from -r requirements.txt (line 34))
Requirement already up-to-date: sampledata in /usr/local/lib/python3.4/site-packages (from django-sampledatahelper==0.3.0->-r requirements.txt (line 3))
Requirement already up-to-date: MarkupSafe in /usr/local/lib/python3.4/site-packages (from jinja2==2.8->-r requirements.txt (line 14))
Requirement already up-to-date: billiard<3.4,>=3.3.0.21 in /usr/local/lib/python3.4/site-packages (from celery==3.1.19->-r requirements.txt (line 23))
Requirement already up-to-date: kombu<3.1,>=3.0.29 in /usr/local/lib/python3.4/site-packages (from celery==3.1.19->-r requirements.txt (line 23))
Requirement already up-to-date: html5lib>=0.999 in /usr/local/lib/python3.4/site-packages (from bleach==1.4.2->-r requirements.txt (line 27))
Requirement already up-to-date: cssselect in /usr/local/lib/python3.4/site-packages (from premailer==2.9.6->-r requirements.txt (line 29))
Requirement already up-to-date: django-transaction-hooks>=0.2 in /usr/local/lib/python3.4/site-packages (from django-transactional-cleanup==0.1.15->-r requirements.txt (line 31))
Requirement already up-to-date: pycrypto>=2.6.1 in /usr/local/lib/python3.4/site-packages (from pyjwkest==1.0.7->-r requirements.txt (line 34))
Requirement already up-to-date: future in /usr/local/lib/python3.4/site-packages (from pyjwkest==1.0.7->-r requirements.txt (line 34))
Requirement already up-to-date: anyjson>=0.3.3 in /usr/local/lib/python3.4/site-packages (from kombu<3.1,>=3.0.29->celery==3.1.19->-r requirements.txt (line 23))
```

Try forcibly pulling the latest image and retry, `docker pull benhutchins/taiga`.

**Comment by chamunks** [comment]
My god why did I miss the fact that you can specifically `docker-compose up -d application` why is this not more obvious!

**Comment by benhutchins** [comment]
@chamunks Try any command with `--help`, like `docker-compose up --help` to learn about all the advance options. There is always a way to drill down to a specific service with `docker-compose`.

Thanks for opening a ticket with `docker/compose`. Based on some the discussion with docker/compose#374 there may be better ways than a sleep statement, which would also allow me to improve [benhutchins/mediawiki](https://github.com/benhutchins/docker-mediawiki/blob/1.25/docker-entrypoint.sh#L9). I'll follow docker/compose#374 for updates, for now I may add a sleep to the startup of the entrypoint for docker-taiga since `docker-compose` is definitely becoming the popular way to handle docker interdependencies.

**Comment by chamunks** [comment]
Docker-compose just cleans up a fair bit of chance for miss steps when using docker.  A docker-compose file either works or it doesn't work a docker run command can tend to work but not include all information required for certain usage cases.  If anything I would suggest maybe adding a delay.sh script and when you launch via docker-compose add the delay.sh as the command to run.  

Then by default set the entrypoint normally. Correct me if my logic is wrong but would that work?

**Comment by benhutchins** [comment]
@chamunks That would work, but just requires those intending to use this project still be aware of that option. However I believe you can do that yourself by doing: `entrypoint: sleep 10 && /docker-entrypoint.sh` in your `docker-compose.yml` file. That should work, since it's a single command.

**Comment by chamunks** [comment]
Thats fair.  Well maybe throwing a docker-compose.yml example with that entry point suggestion would be smart until [docker/compose#374](https://github.com/docker/compose/issues/374) gets sorted.

**Comment by benhutchins** [comment]
@chamunks So docker requires entrypoints to be files, so my solution didn't work, and using `command` wouldn't work because the entrypoint runs `checkdb.py` before calling the command so I've implemented a simple sleep environmental variable that will address this for now.

**Comment by chamunks** [comment]
Technically you could stuff the command into the containers $PATH and it would pretend to be a command.

Also the syntax below worked for me.

    CMD ["java", "-Xmx2G", "-Xincgc", "-jar", "BungeeCord.jar"]

For some reason this worked for a multi argument CMD so it might apply to ENTRYPOINT as well.

**Comment by jasl8r** [comment]
Well it still appears as though @chamunks original issue is due to using https://github.com/benhutchins/docker-taiga-example which pulls an image from dockerhub using taiga 1.8.0.  @benhutchins I verified that I had the latest image from docker, and it's 1.8.0.  In fact I've never worked with Taiga until today.  I'll build my own image, but in the mean time should there really be a bug over on https://github.com/benhutchins/docker-taiga-example?
